const SET_JOKE = "SET_JOKE"
const CLEAR_JOKE = "CLEAR_JOKE"
const REVEAL_PUNCHLINE = "REVEAL_PUNCHLINE"
const HIDE_PUNCHLINE = "HIDE_PUNCHLINE"
const SHOW_ANSWER_BUTTON = "SHOW_ANSWER_BUTTON"
const HIDE_ANSWER_BUTTON = "HIDE_ANSWER_BUTTON"

export {
    SET_JOKE,
    CLEAR_JOKE,
    REVEAL_PUNCHLINE,
    HIDE_PUNCHLINE,
    SHOW_ANSWER_BUTTON,
    HIDE_ANSWER_BUTTON
}